#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  test.pro
# Template: app
# Command: /Users/himanshurewar/qt/5.11.0/ios/bin/qmake -o test.xcodeproj/project.pbxproj test.pro -spec macx-xcode -config release
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/himanshurewar/qt/5.11.0/ios/bin/qmake
test.xcodeproj/project.pbxproj: test.pro ../Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf ../qt/5.11.0/ios/mkspecs/features/spec_pre.prf \
		../qt/5.11.0/ios/mkspecs/qdevice.pri \
		../Qt/5.11.0/ios/mkspecs/features/device_config.prf \
		../Qt/5.11.0/ios/mkspecs/common/unix.conf \
		../Qt/5.11.0/ios/mkspecs/common/mac.conf \
		../Qt/5.11.0/ios/mkspecs/common/uikit.conf \
		../Qt/5.11.0/ios/mkspecs/common/ios.conf \
		../Qt/5.11.0/ios/mkspecs/common/sanitize.conf \
		../Qt/5.11.0/ios/mkspecs/common/gcc-base.conf \
		../Qt/5.11.0/ios/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.11.0/ios/mkspecs/common/clang.conf \
		../Qt/5.11.0/ios/mkspecs/common/clang-mac.conf \
		../Qt/5.11.0/ios/mkspecs/common/uikit/clang.conf \
		../Qt/5.11.0/ios/mkspecs/common/uikit/qmake.conf \
		../qt/5.11.0/ios/mkspecs/qconfig.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_charts.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_core.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_core_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_gui.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_help.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_help_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_location.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_location_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_locationlabs.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_locationlabs_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_network.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_network_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qml.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quick.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_script.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_script_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_sql.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_svg.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_webview.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_xml.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qico.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qios.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../qt/5.11.0/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../Qt/5.11.0/ios/mkspecs/features/qt_functions.prf \
		../Qt/5.11.0/ios/mkspecs/features/qt_config.prf \
		../Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf \
		../qt/5.11.0/ios/mkspecs/macx-xcode/qmake.conf \
		../Qt/5.11.0/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.11.0/ios/mkspecs/features/exclusive_builds.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/sdk.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/sdk.prf \
		../Qt/5.11.0/ios/mkspecs/features/toolchain.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/toolchain.prf \
		../Qt/5.11.0/ios/mkspecs/features/default_pre.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/default_pre.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/default_pre.prf \
		../Qt/5.11.0/ios/mkspecs/features/resolve_config.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/resolve_config.prf \
		../Qt/5.11.0/ios/mkspecs/features/default_post.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/default_post.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/default_post.prf \
		../Qt/5.11.0/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/objective_c.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/mac.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/bitcode.prf \
		../Qt/5.11.0/ios/mkspecs/features/warn_on.prf \
		../qt/5.11.0/ios/plugins/platforms/libqios.prl \
		../Qt/5.11.0/ios/mkspecs/features/qt.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/qt.prf \
		../Qt/5.11.0/ios/mkspecs/features/resources.prf \
		../Qt/5.11.0/ios/mkspecs/features/moc.prf \
		../Qt/5.11.0/ios/mkspecs/features/unix/opengl.prf \
		../Qt/5.11.0/ios/mkspecs/features/uic.prf \
		../Qt/5.11.0/ios/mkspecs/features/unix/thread.prf \
		../Qt/5.11.0/ios/mkspecs/features/qmake_use.prf \
		../Qt/5.11.0/ios/mkspecs/features/file_copies.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/rez.prf \
		../Qt/5.11.0/ios/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.11.0/ios/mkspecs/features/testcase_targets.prf \
		../Qt/5.11.0/ios/mkspecs/features/uikit/testcase_targets.prf \
		../Qt/5.11.0/ios/mkspecs/features/exceptions.prf \
		../Qt/5.11.0/ios/mkspecs/features/yacc.prf \
		../Qt/5.11.0/ios/mkspecs/features/lex.prf \
		test.pro \
		../Qt/5.11.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		../Qt/5.11.0/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../qt/5.11.0/ios/lib/libQt5FontDatabaseSupport.prl \
		../qt/5.11.0/ios/lib/libqtfreetype.prl \
		../qt/5.11.0/ios/lib/libQt5GraphicsSupport.prl \
		../qt/5.11.0/ios/lib/libQt5ClipboardSupport.prl \
		../qt/5.11.0/ios/lib/libQt5Gui.prl \
		../qt/5.11.0/ios/lib/libqtlibpng.prl \
		../qt/5.11.0/ios/lib/libqtharfbuzz.prl \
		../qt/5.11.0/ios/lib/libQt5Core.prl \
		../qt/5.11.0/ios/lib/libqtpcre2.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqgif.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqicns.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqico.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqjpeg.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqmacheif.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqmacjp2.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqtga.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqtiff.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqwbmp.prl \
		../qt/5.11.0/ios/plugins/imageformats/libqwebp.prl \
		../qt/5.11.0/ios/lib/libQt5OpenGL.prl \
		../qt/5.11.0/ios/lib/libQt5Widgets.prl
	$(QMAKE) -o test.xcodeproj/project.pbxproj test.pro -spec macx-xcode -config release
../qt/5.11.0/ios/mkspecs/features/spec_pre.prf:
../qt/5.11.0/ios/mkspecs/qdevice.pri:
../Qt/5.11.0/ios/mkspecs/features/device_config.prf:
../Qt/5.11.0/ios/mkspecs/common/unix.conf:
../Qt/5.11.0/ios/mkspecs/common/mac.conf:
../Qt/5.11.0/ios/mkspecs/common/uikit.conf:
../Qt/5.11.0/ios/mkspecs/common/ios.conf:
../Qt/5.11.0/ios/mkspecs/common/sanitize.conf:
../Qt/5.11.0/ios/mkspecs/common/gcc-base.conf:
../Qt/5.11.0/ios/mkspecs/common/gcc-base-mac.conf:
../Qt/5.11.0/ios/mkspecs/common/clang.conf:
../Qt/5.11.0/ios/mkspecs/common/clang-mac.conf:
../Qt/5.11.0/ios/mkspecs/common/uikit/clang.conf:
../Qt/5.11.0/ios/mkspecs/common/uikit/qmake.conf:
../qt/5.11.0/ios/mkspecs/qconfig.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_charts.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_charts_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_core.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_core_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_gui.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_gui_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_help.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_help_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_location.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_location_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_locationlabs.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_locationlabs_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_network.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_network_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qml.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qml_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quick.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quick_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_script.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_script_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_sql.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_sql_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_svg.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_svg_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_webview.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_webview_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_xml.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_xml_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgif.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qicns.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qico.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qios.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtga.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../qt/5.11.0/ios/mkspecs/modules/qt_plugin_scene2d.pri:
../Qt/5.11.0/ios/mkspecs/features/qt_functions.prf:
../Qt/5.11.0/ios/mkspecs/features/qt_config.prf:
../Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf:
../qt/5.11.0/ios/mkspecs/macx-xcode/qmake.conf:
../Qt/5.11.0/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.11.0/ios/mkspecs/features/exclusive_builds.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/sdk.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/sdk.prf:
../Qt/5.11.0/ios/mkspecs/features/toolchain.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/toolchain.prf:
../Qt/5.11.0/ios/mkspecs/features/default_pre.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/default_pre.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/default_pre.prf:
../Qt/5.11.0/ios/mkspecs/features/resolve_config.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/resolve_config.prf:
../Qt/5.11.0/ios/mkspecs/features/default_post.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/default_post.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/default_post.prf:
../Qt/5.11.0/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/objective_c.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/mac.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/bitcode.prf:
../Qt/5.11.0/ios/mkspecs/features/warn_on.prf:
../qt/5.11.0/ios/plugins/platforms/libqios.prl:
../Qt/5.11.0/ios/mkspecs/features/qt.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/qt.prf:
../Qt/5.11.0/ios/mkspecs/features/resources.prf:
../Qt/5.11.0/ios/mkspecs/features/moc.prf:
../Qt/5.11.0/ios/mkspecs/features/unix/opengl.prf:
../Qt/5.11.0/ios/mkspecs/features/uic.prf:
../Qt/5.11.0/ios/mkspecs/features/unix/thread.prf:
../Qt/5.11.0/ios/mkspecs/features/qmake_use.prf:
../Qt/5.11.0/ios/mkspecs/features/file_copies.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/rez.prf:
../Qt/5.11.0/ios/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.11.0/ios/mkspecs/features/testcase_targets.prf:
../Qt/5.11.0/ios/mkspecs/features/uikit/testcase_targets.prf:
../Qt/5.11.0/ios/mkspecs/features/exceptions.prf:
../Qt/5.11.0/ios/mkspecs/features/yacc.prf:
../Qt/5.11.0/ios/mkspecs/features/lex.prf:
test.pro:
../Qt/5.11.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
../Qt/5.11.0/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../qt/5.11.0/ios/lib/libQt5FontDatabaseSupport.prl:
../qt/5.11.0/ios/lib/libqtfreetype.prl:
../qt/5.11.0/ios/lib/libQt5GraphicsSupport.prl:
../qt/5.11.0/ios/lib/libQt5ClipboardSupport.prl:
../qt/5.11.0/ios/lib/libQt5Gui.prl:
../qt/5.11.0/ios/lib/libqtlibpng.prl:
../qt/5.11.0/ios/lib/libqtharfbuzz.prl:
../qt/5.11.0/ios/lib/libQt5Core.prl:
../qt/5.11.0/ios/lib/libqtpcre2.prl:
../qt/5.11.0/ios/plugins/imageformats/libqgif.prl:
../qt/5.11.0/ios/plugins/imageformats/libqicns.prl:
../qt/5.11.0/ios/plugins/imageformats/libqico.prl:
../qt/5.11.0/ios/plugins/imageformats/libqjpeg.prl:
../qt/5.11.0/ios/plugins/imageformats/libqmacheif.prl:
../qt/5.11.0/ios/plugins/imageformats/libqmacjp2.prl:
../qt/5.11.0/ios/plugins/imageformats/libqtga.prl:
../qt/5.11.0/ios/plugins/imageformats/libqtiff.prl:
../qt/5.11.0/ios/plugins/imageformats/libqwbmp.prl:
../qt/5.11.0/ios/plugins/imageformats/libqwebp.prl:
../qt/5.11.0/ios/lib/libQt5OpenGL.prl:
../qt/5.11.0/ios/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -o test.xcodeproj/project.pbxproj test.pro -spec macx-xcode -config release

qmake_all: FORCE

