#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  test.pro
# Template: app
# Command: /Users/himanshurewar/qt/5.11.0/ios/bin/qmake -o test.xcodeproj/project.pbxproj test.pro -spec macx-xcode -config release
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/himanshurewar/qt/5.11.0/ios/bin/moc
UIC       = /Users/himanshurewar/qt/5.11.0/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../Qt/5.11.0/ios/mkspecs/common/uikit -I../qt/5.11.0/ios/include -I../qt/5.11.0/ios/include/QtOpenGL -I../qt/5.11.0/ios/include/QtWidgets -I../qt/5.11.0/ios/include/QtGui -I../qt/5.11.0/ios/include/QtCore -I. -I. -I../Qt/5.11.0/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_mainwindow.cpp moc_glwidget.cpp ui_mainwindow.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp
moc_mainwindow.cpp: ../qt/5.11.0/ios/include/QtWidgets/QMainWindow \
		mainwindow.h \
		../qt/5.11.0/ios/bin/moc
	/Users/himanshurewar/qt/5.11.0/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=7 -D__clang_minor__=0 -D__clang_patchlevel__=2 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/himanshurewar/Qt/5.11.0/ios/mkspecs/macx-ios-clang -I/Users/himanshurewar/test -I/Users/himanshurewar/Qt/5.11.0/ios/mkspecs/common/uikit -I/Users/himanshurewar/qt/5.11.0/ios/include -I/Users/himanshurewar/qt/5.11.0/ios/include/QtOpenGL -I/Users/himanshurewar/qt/5.11.0/ios/include/QtWidgets -I/Users/himanshurewar/qt/5.11.0/ios/include/QtGui -I/Users/himanshurewar/qt/5.11.0/ios/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: ../qt/5.11.0/ios/include/QtOpenGL/QGLWidget \
		../qt/5.11.0/ios/include/QtCore/QTimer \
		glwidget.h \
		../qt/5.11.0/ios/bin/moc
	/Users/himanshurewar/qt/5.11.0/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=7 -D__clang_minor__=0 -D__clang_patchlevel__=2 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/himanshurewar/Qt/5.11.0/ios/mkspecs/macx-ios-clang -I/Users/himanshurewar/test -I/Users/himanshurewar/Qt/5.11.0/ios/mkspecs/common/uikit -I/Users/himanshurewar/qt/5.11.0/ios/include -I/Users/himanshurewar/qt/5.11.0/ios/include/QtOpenGL -I/Users/himanshurewar/qt/5.11.0/ios/include/QtWidgets -I/Users/himanshurewar/qt/5.11.0/ios/include/QtGui -I/Users/himanshurewar/qt/5.11.0/ios/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include glwidget.h -o moc_glwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../qt/5.11.0/ios/bin/uic \
		glwidget.h \
		../qt/5.11.0/ios/include/QtOpenGL/QGLWidget \
		../qt/5.11.0/ios/include/QtCore/QTimer
	/Users/himanshurewar/qt/5.11.0/ios/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

